export interface StateInfo {
  name: string;
  regionId: string;
}

const NIGERIA_STATES: StateInfo[] = [
  { name: 'Abia', regionId: 'NG-AB' },
  { name: 'Adamawa', regionId: 'NG-AD' },
  { name: 'Akwa Ibom', regionId: 'NG-AK' },
  { name: 'Anambra', regionId: 'NG-AN' },
  { name: 'Bauchi', regionId: 'NG-BA' },
  { name: 'Bayelsa', regionId: 'NG-BY' },
  { name: 'Benue', regionId: 'NG-BE' },
  { name: 'Borno', regionId: 'NG-BO' },
  { name: 'Cross River', regionId: 'NG-CR' },
  { name: 'Delta', regionId: 'NG-DE' },
  { name: 'Ebonyi', regionId: 'NG-EB' },
  { name: 'Edo', regionId: 'NG-ED' },
  { name: 'Ekiti', regionId: 'NG-EK' },
  { name: 'Enugu', regionId: 'NG-EN' },
  { name: 'FCT Abuja', regionId: 'NG-FC' },
  { name: 'Gombe', regionId: 'NG-GO' },
  { name: 'Imo', regionId: 'NG-IM' },
  { name: 'Jigawa', regionId: 'NG-JI' },
  { name: 'Kaduna', regionId: 'NG-KD' },
  { name: 'Kano', regionId: 'NG-KN' },
  { name: 'Katsina', regionId: 'NG-KT' },
  { name: 'Kebbi', regionId: 'NG-KE' },
  { name: 'Kogi', regionId: 'NG-KO' },
  { name: 'Kwara', regionId: 'NG-KW' },
  { name: 'Lagos', regionId: 'NG-LA' },
  { name: 'Nasarawa', regionId: 'NG-NA' },
  { name: 'Niger', regionId: 'NG-NI' },
  { name: 'Ogun', regionId: 'NG-OG' },
  { name: 'Ondo', regionId: 'NG-ON' },
  { name: 'Osun', regionId: 'NG-OS' },
  { name: 'Oyo', regionId: 'NG-OY' },
  { name: 'Plateau', regionId: 'NG-PL' },
  { name: 'Rivers', regionId: 'NG-RI' },
  { name: 'Sokoto', regionId: 'NG-SO' },
  { name: 'Taraba', regionId: 'NG-TA' },
  { name: 'Yobe', regionId: 'NG-YO' },
  { name: 'Zamfara', regionId: 'NG-ZA' },
];

const UNITED_STATES_STATES: StateInfo[] = [
  { name: 'Alabama', regionId: 'US-AL' },
  { name: 'Alaska', regionId: 'US-AK' },
  { name: 'Arizona', regionId: 'US-AZ' },
  { name: 'Arkansas', regionId: 'US-AR' },
  { name: 'California', regionId: 'US-CA' },
  { name: 'Colorado', regionId: 'US-CO' },
  { name: 'Connecticut', regionId: 'US-CT' },
  { name: 'Delaware', regionId: 'US-DE' },
  { name: 'Florida', regionId: 'US-FL' },
  { name: 'Georgia', regionId: 'US-GA' },
  { name: 'Hawaii', regionId: 'US-HI' },
  { name: 'Idaho', regionId: 'US-ID' },
  { name: 'Illinois', regionId: 'US-IL' },
  { name: 'Indiana', regionId: 'US-IN' },
  { name: 'Iowa', regionId: 'US-IA' },
  { name: 'Kansas', regionId: 'US-KS' },
  { name: 'Kentucky', regionId: 'US-KY' },
  { name: 'Louisiana', regionId: 'US-LA' },
  { name: 'Maine', regionId: 'US-ME' },
  { name: 'Maryland', regionId: 'US-MD' },
  { name: 'Massachusetts', regionId: 'US-MA' },
  { name: 'Michigan', regionId: 'US-MI' },
  { name: 'Minnesota', regionId: 'US-MN' },
  { name: 'Mississippi', regionId: 'US-MS' },
  { name: 'Missouri', regionId: 'US-MO' },
  { name: 'Montana', regionId: 'US-MT' },
  { name: 'Nebraska', regionId: 'US-NE' },
  { name: 'Nevada', regionId: 'US-NV' },
  { name: 'New Hampshire', regionId: 'US-NH' },
  { name: 'New Jersey', regionId: 'US-NJ' },
  { name: 'New Mexico', regionId: 'US-NM' },
  { name: 'New York', regionId: 'US-NY' },
  { name: 'North Carolina', regionId: 'US-NC' },
  { name: 'North Dakota', regionId: 'US-ND' },
  { name: 'Ohio', regionId: 'US-OH' },
  { name: 'Oklahoma', regionId: 'US-OK' },
  { name: 'Oregon', regionId: 'US-OR' },
  { name: 'Pennsylvania', regionId: 'US-PA' },
  { name: 'Rhode Island', regionId: 'US-RI' },
  { name: 'South Carolina', regionId: 'US-SC' },
  { name: 'South Dakota', regionId: 'US-SD' },
  { name: 'Tennessee', regionId: 'US-TN' },
  { name: 'Texas', regionId: 'US-TX' },
  { name: 'Utah', regionId: 'US-UT' },
  { name: 'Vermont', regionId: 'US-VT' },
  { name: 'Virginia', regionId: 'US-VA' },
  { name: 'Washington', regionId: 'US-WA' },
  { name: 'West Virginia', regionId: 'US-WV' },
  { name: 'Wisconsin', regionId: 'US-WI' },
  { name: 'Wyoming', regionId: 'US-WY' },
];

const CANADA_PROVINCES: StateInfo[] = [
  { name: 'Alberta', regionId: 'CA-AB' },
  { name: 'British Columbia', regionId: 'CA-BC' },
  { name: 'Manitoba', regionId: 'CA-MB' },
  { name: 'New Brunswick', regionId: 'CA-NB' },
  { name: 'Newfoundland and Labrador', regionId: 'CA-NL' },
  { name: 'Northwest Territories', regionId: 'CA-NT' },
  { name: 'Nova Scotia', regionId: 'CA-NS' },
  { name: 'Nunavut', regionId: 'CA-NU' },
  { name: 'Ontario', regionId: 'CA-ON' },
  { name: 'Prince Edward Island', regionId: 'CA-PE' },
  { name: 'Quebec', regionId: 'CA-QC' },
  { name: 'Saskatchewan', regionId: 'CA-SK' },
  { name: 'Yukon', regionId: 'CA-YT' },
];

const UK_REGIONS: StateInfo[] = [
  { name: 'England', regionId: 'GB-ENG' },
  { name: 'Scotland', regionId: 'GB-SCT' },
  { name: 'Wales', regionId: 'GB-WLS' },
  { name: 'Northern Ireland', regionId: 'GB-NIR' },
];

const GHANA_REGIONS: StateInfo[] = [
  { name: 'Greater Accra', regionId: 'GH-AA' },
  { name: 'Ashanti', regionId: 'GH-AH' },
  { name: 'Western', regionId: 'GH-WP' },
  { name: 'Eastern', regionId: 'GH-EP' },
  { name: 'Central', regionId: 'GH-CP' },
  { name: 'Northern', regionId: 'GH-NP' },
  { name: 'Volta', regionId: 'GH-TV' },
  { name: 'Upper East', regionId: 'GH-UE' },
  { name: 'Upper West', regionId: 'GH-UW' },
  { name: 'Brong-Ahafo', regionId: 'GH-BA' },
];

const KENYA_COUNTIES: StateInfo[] = [
  { name: 'Nairobi', regionId: 'KE-110' },
  { name: 'Mombasa', regionId: 'KE-300' },
  { name: 'Kisumu', regionId: 'KE-400' },
  { name: 'Nakuru', regionId: 'KE-320' },
  { name: 'Eldoret', regionId: 'KE-270' },
  { name: 'Thika', regionId: 'KE-220' },
  { name: 'Malindi', regionId: 'KE-301' },
  { name: 'Nyeri', regionId: 'KE-140' },
  { name: 'Machakos', regionId: 'KE-210' },
  { name: 'Meru', regionId: 'KE-120' },
];

const SOUTH_AFRICA_PROVINCES: StateInfo[] = [
  { name: 'Gauteng', regionId: 'ZA-GT' },
  { name: 'Western Cape', regionId: 'ZA-WC' },
  { name: 'KwaZulu-Natal', regionId: 'ZA-KZN' },
  { name: 'Eastern Cape', regionId: 'ZA-EC' },
  { name: 'Limpopo', regionId: 'ZA-LP' },
  { name: 'Mpumalanga', regionId: 'ZA-MP' },
  { name: 'North West', regionId: 'ZA-NW' },
  { name: 'Free State', regionId: 'ZA-FS' },
  { name: 'Northern Cape', regionId: 'ZA-NC' },
];

const UAE_EMIRATES: StateInfo[] = [
  { name: 'Dubai', regionId: 'AE-DU' },
  { name: 'Abu Dhabi', regionId: 'AE-AZ' },
  { name: 'Sharjah', regionId: 'AE-SH' },
  { name: 'Ajman', regionId: 'AE-AJ' },
  { name: 'Fujairah', regionId: 'AE-FU' },
  { name: 'Ras Al Khaimah', regionId: 'AE-RK' },
  { name: 'Umm Al Quwain', regionId: 'AE-UQ' },
];

const AUSTRALIA_STATES: StateInfo[] = [
  { name: 'New South Wales', regionId: 'AU-NSW' },
  { name: 'Victoria', regionId: 'AU-VIC' },
  { name: 'Queensland', regionId: 'AU-QLD' },
  { name: 'Western Australia', regionId: 'AU-WA' },
  { name: 'South Australia', regionId: 'AU-SA' },
  { name: 'Tasmania', regionId: 'AU-TAS' },
  { name: 'Australian Capital Territory', regionId: 'AU-ACT' },
  { name: 'Northern Territory', regionId: 'AU-NT' },
];

const GERMANY_STATES: StateInfo[] = [
  { name: 'Bavaria', regionId: 'DE-BY' },
  { name: 'North Rhine-Westphalia', regionId: 'DE-NW' },
  { name: 'Baden-Württemberg', regionId: 'DE-BW' },
  { name: 'Berlin', regionId: 'DE-BE' },
  { name: 'Hamburg', regionId: 'DE-HH' },
  { name: 'Hesse', regionId: 'DE-HE' },
  { name: 'Saxony', regionId: 'DE-SN' },
  { name: 'Lower Saxony', regionId: 'DE-NI' },
  { name: 'Brandenburg', regionId: 'DE-BB' },
  { name: 'Rhineland-Palatinate', regionId: 'DE-RP' },
  { name: 'Saxony-Anhalt', regionId: 'DE-ST' },
  { name: 'Thuringia', regionId: 'DE-TH' },
  { name: 'Schleswig-Holstein', regionId: 'DE-SH' },
  { name: 'Mecklenburg-Vorpommern', regionId: 'DE-MV' },
  { name: 'Saarland', regionId: 'DE-SL' },
  { name: 'Bremen', regionId: 'DE-HB' },
];

const FRANCE_REGIONS: StateInfo[] = [
  { name: 'Île-de-France', regionId: 'FR-IDF' },
  { name: 'Auvergne-Rhône-Alpes', regionId: 'FR-ARA' },
  { name: 'Nouvelle-Aquitaine', regionId: 'FR-NAQ' },
  { name: 'Occitanie', regionId: 'FR-OCC' },
  { name: 'Hauts-de-France', regionId: 'FR-HDF' },
  { name: 'Grand Est', regionId: 'FR-GES' },
  { name: 'Provence-Alpes-Côte d\'Azur', regionId: 'FR-PAC' },
  { name: 'Pays de la Loire', regionId: 'FR-PDL' },
  { name: 'Normandie', regionId: 'FR-NOR' },
  { name: 'Bretagne', regionId: 'FR-BRE' },
  { name: 'Bourgogne-Franche-Comté', regionId: 'FR-BFC' },
  { name: 'Centre-Val de Loire', regionId: 'FR-CVL' },
  { name: 'Corsica', regionId: 'FR-COR' },
];

const INDIA_STATES: StateInfo[] = [
  { name: 'Andhra Pradesh', regionId: 'IN-AP' },
  { name: 'Arunachal Pradesh', regionId: 'IN-AR' },
  { name: 'Assam', regionId: 'IN-AS' },
  { name: 'Bihar', regionId: 'IN-BR' },
  { name: 'Chhattisgarh', regionId: 'IN-CT' },
  { name: 'Goa', regionId: 'IN-GA' },
  { name: 'Gujarat', regionId: 'IN-GJ' },
  { name: 'Haryana', regionId: 'IN-HR' },
  { name: 'Himachal Pradesh', regionId: 'IN-HP' },
  { name: 'Jharkhand', regionId: 'IN-JH' },
  { name: 'Karnataka', regionId: 'IN-KA' },
  { name: 'Kerala', regionId: 'IN-KL' },
  { name: 'Madhya Pradesh', regionId: 'IN-MP' },
  { name: 'Maharashtra', regionId: 'IN-MH' },
  { name: 'Manipur', regionId: 'IN-MN' },
  { name: 'Meghalaya', regionId: 'IN-ML' },
  { name: 'Mizoram', regionId: 'IN-MZ' },
  { name: 'Nagaland', regionId: 'IN-NL' },
  { name: 'Odisha', regionId: 'IN-OR' },
  { name: 'Punjab', regionId: 'IN-PB' },
  { name: 'Rajasthan', regionId: 'IN-RJ' },
  { name: 'Sikkim', regionId: 'IN-SK' },
  { name: 'Tamil Nadu', regionId: 'IN-TN' },
  { name: 'Telangana', regionId: 'IN-TG' },
  { name: 'Tripura', regionId: 'IN-TR' },
  { name: 'Uttar Pradesh', regionId: 'IN-UP' },
  { name: 'Uttarakhand', regionId: 'IN-UT' },
  { name: 'West Bengal', regionId: 'IN-WB' },
  { name: 'Delhi', regionId: 'IN-DL' },
];

const JAPAN_PREFECTURES: StateInfo[] = [
  { name: 'Tokyo', regionId: 'JP-13' },
  { name: 'Osaka', regionId: 'JP-27' },
  { name: 'Kanagawa', regionId: 'JP-14' },
  { name: 'Aichi', regionId: 'JP-23' },
  { name: 'Saitama', regionId: 'JP-11' },
  { name: 'Chiba', regionId: 'JP-12' },
  { name: 'Hyogo', regionId: 'JP-28' },
  { name: 'Hokkaido', regionId: 'JP-01' },
  { name: 'Fukuoka', regionId: 'JP-40' },
  { name: 'Kyoto', regionId: 'JP-26' },
];

const BRAZIL_STATES: StateInfo[] = [
  { name: 'São Paulo', regionId: 'BR-SP' },
  { name: 'Rio de Janeiro', regionId: 'BR-RJ' },
  { name: 'Minas Gerais', regionId: 'BR-MG' },
  { name: 'Bahia', regionId: 'BR-BA' },
  { name: 'Paraná', regionId: 'BR-PR' },
  { name: 'Rio Grande do Sul', regionId: 'BR-RS' },
  { name: 'Pernambuco', regionId: 'BR-PE' },
  { name: 'Ceará', regionId: 'BR-CE' },
  { name: 'Pará', regionId: 'BR-PA' },
  { name: 'Santa Catarina', regionId: 'BR-SC' },
  { name: 'Goiás', regionId: 'BR-GO' },
  { name: 'Amazonas', regionId: 'BR-AM' },
  { name: 'Maranhão', regionId: 'BR-MA' },
  { name: 'Espírito Santo', regionId: 'BR-ES' },
  { name: 'Mato Grosso', regionId: 'BR-MT' },
  { name: 'Rio Grande do Norte', regionId: 'BR-RN' },
  { name: 'Alagoas', regionId: 'BR-AL' },
  { name: 'Piauí', regionId: 'BR-PI' },
  { name: 'Paraíba', regionId: 'BR-PB' },
  { name: 'Mato Grosso do Sul', regionId: 'BR-MS' },
  { name: 'Sergipe', regionId: 'BR-SE' },
  { name: 'Rondônia', regionId: 'BR-RO' },
  { name: 'Tocantins', regionId: 'BR-TO' },
  { name: 'Acre', regionId: 'BR-AC' },
  { name: 'Roraima', regionId: 'BR-RR' },
  { name: 'Amapá', regionId: 'BR-AP' },
  { name: 'Distrito Federal', regionId: 'BR-DF' },
];

const MEXICO_STATES: StateInfo[] = [
  { name: 'Aguascalientes', regionId: 'MX-AG' },
  { name: 'Baja California', regionId: 'MX-BC' },
  { name: 'Baja California Sur', regionId: 'MX-BS' },
  { name: 'Campeche', regionId: 'MX-CM' },
  { name: 'Chiapas', regionId: 'MX-CS' },
  { name: 'Chihuahua', regionId: 'MX-CH' },
  { name: 'Ciudad de México', regionId: 'MX-DF' },
  { name: 'Coahuila', regionId: 'MX-CO' },
  { name: 'Colima', regionId: 'MX-CL' },
  { name: 'Durango', regionId: 'MX-DG' },
  { name: 'Guanajuato', regionId: 'MX-GT' },
  { name: 'Guerrero', regionId: 'MX-GR' },
  { name: 'Hidalgo', regionId: 'MX-HG' },
  { name: 'Jalisco', regionId: 'MX-JA' },
  { name: 'México', regionId: 'MX-ME' },
  { name: 'Michoacán', regionId: 'MX-MI' },
  { name: 'Morelos', regionId: 'MX-MO' },
  { name: 'Nayarit', regionId: 'MX-NA' },
  { name: 'Nuevo León', regionId: 'MX-NL' },
  { name: 'Oaxaca', regionId: 'MX-OA' },
  { name: 'Puebla', regionId: 'MX-PU' },
  { name: 'Querétaro', regionId: 'MX-QT' },
  { name: 'Quintana Roo', regionId: 'MX-QR' },
  { name: 'San Luis Potosí', regionId: 'MX-SL' },
  { name: 'Sinaloa', regionId: 'MX-SI' },
  { name: 'Sonora', regionId: 'MX-SO' },
  { name: 'Tabasco', regionId: 'MX-TB' },
  { name: 'Tamaulipas', regionId: 'MX-TM' },
  { name: 'Tlaxcala', regionId: 'MX-TL' },
  { name: 'Veracruz', regionId: 'MX-VE' },
  { name: 'Yucatán', regionId: 'MX-YU' },
  { name: 'Zacatecas', regionId: 'MX-ZA' },
];

const STATES_BY_COUNTRY: Record<string, StateInfo[]> = {
  NG: NIGERIA_STATES,
  US: UNITED_STATES_STATES,
  CA: CANADA_PROVINCES,
  GB: UK_REGIONS,
  GH: GHANA_REGIONS,
  KE: KENYA_COUNTIES,
  ZA: SOUTH_AFRICA_PROVINCES,
  AE: UAE_EMIRATES,
  AU: AUSTRALIA_STATES,
  DE: GERMANY_STATES,
  FR: FRANCE_REGIONS,
  IN: INDIA_STATES,
  JP: JAPAN_PREFECTURES,
  BR: BRAZIL_STATES,
  MX: MEXICO_STATES,
};

export function getStatesByCountry(countryCode: string): StateInfo[] {
  return STATES_BY_COUNTRY[countryCode] ?? [];
}

export function getStateLabel(countryCode: string): string {
  const labels: Record<string, string> = {
    US: 'State',
    CA: 'Province',
    GB: 'Region',
    AU: 'State / Territory',
    JP: 'Prefecture',
    IN: 'State',
    BR: 'State',
    MX: 'State',
    AE: 'Emirate',
    GH: 'Region',
    KE: 'County',
    ZA: 'Province',
    DE: 'State',
    FR: 'Region',
  };
  return labels[countryCode] ?? 'State / Region';
}
